
platform :ios, '9.0'

target 'Animation' do
  use_frameworks!
  pod 'AFNetworking','~> 3.0'
  pod 'SDWebImage','~> 2.0'
  pod 'ReactiveCocoa','~>2.5.0-alpha-1'
  pod 'Aspects'
  pod 'MLeaksFinder'
  pod 'Masonry'
  pod 'WAAppRouting'
end
